# Generated by Django 2.0.2 on 2020-07-08 10:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200708_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 8, 10, 43, 26, 941937, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
