# Generated by Django 2.0.2 on 2020-07-15 14:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200708_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 14, 28, 57, 892113, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
