# Generated by Django 2.0.2 on 2020-07-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20200708_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.TextField(blank=True, null=True, verbose_name='Enlace'),
        ),
    ]
